name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
        run: echo "Environment variables set"

      - name: Run flake8
        run: flake8

      - name: Run tests
        timeout-minutes: 5
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
        run: |
          export DJANGO_SETTINGS_MODULE=library_api.settings
          python manage.py test
